name: Build test image
on:
    push:
    pull_request:

jobs:
    build-image:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - uses: actions/checkout@v3
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Log in to the Container registry
              uses: docker/login-action@v2
              with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v2
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}

            - name: Extract metadata from Github
              id: meta
              uses: docker/metadata-action@v4
              with:
                images: |
                    docker.io/calyptiaci/provenance_test
                    ghcr.io/${{ github.repository }}
                tags: |
                    type=sha
                    # set latest tag for default branch
                    type=raw,value=latest,enable={{is_default_branch}}
                    # branch event
                    type=ref,event=branch
                    # tag event
                    type=ref,event=tag
                    # pull request event
                    type=ref,event=pr

            - name: Build the image
              id: build_push
              uses: docker/build-push-action@v4
              with:
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}
                platforms: linux/amd64
                provenance: false
                push: true
                load: false
